# Generated by Django 3.0.3 on 2020-02-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200213_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_dodania',
            field=models.DateTimeField(),
        ),
    ]
