# Generated by Django 3.0.3 on 2020-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200213_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
    ]
