# Generated by Django 3.0.3 on 2020-02-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200214_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_author', models.CharField(max_length=200)),
                ('com_text', models.TextField()),
                ('com_created_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comments'),
        ),
    ]
