# Generated by Django 3.0.3 on 2020-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comments_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
