# Generated by Django 3.0.3 on 2020-03-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200330_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='com_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='com_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='com_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comments',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
