# Generated by Django 3.0.3 on 2020-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comments',
            field=models.TextField(max_length=2000),
        ),
    ]
