# Generated by Django 3.0.3 on 2020-04-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_question_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
