# Generated by Django 3.0.3 on 2020-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_question_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
