# Generated by Django 3.0.3 on 2020-04-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_comments_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='approved_comment',
            new_name='active',
        ),
    ]
