# Generated by Django 3.0.3 on 2020-04-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200402_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
